services:
  frontend:
    container_name: ${FRONTEND_HOST}
    build:
        context: .
        dockerfile: Dockerfile.frontend.dev
    ports:
        - ${FRONTEND_PORT}:${FRONTEND_PORT}
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /frontend
  backend:
    container_name: ${BACKEND_HOST}
    build:
        context: .
        dockerfile: Dockerfile.backend.dev
    ports:
        - ${BACKEND_PORT}:${BACKEND_PORT}
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /backend
